/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_Hello */

#ifndef _Included_com_example_test_Hello
#define _Included_com_example_test_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_Hello_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_example_test_Hello
 * Method:    sayHi
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_test_Hello_sayHi
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
